[package]
name = "alt_bn128_rv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alt_bn128 = { path="../alt_bn128" }
