name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo check --no-default-features
        cargo build --release --verbose
    - name: Run tests
      run: |
        cargo test --release --no-default-features
        cargo test --release --verbose
    - name: Install minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Run benches
      run: |
        cargo +nightly bench --bench api
        lscpu
   
  build-and-test-on-macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Install minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Build
      run: |
        cargo check --no-default-features
        cargo build --release --verbose
    - name: Run tests
      run: |
        cargo test --release --no-default-features
        cargo test --release --verbose
    - name: Run benches
      run: |
        cargo +nightly bench --bench api
        sysctl -n machdep.cpu.brand_string
        sysctl -a | grep machdep.cpu
